### ISSUE TITLE
rateable plugin is not working with remote pagination 

### ISSUE THREAD

**Issue by viseth** [gpc/rateable#1]
Hello,
The issue is that the rateable is not correctly render after the remotepagination ajax call. Indeed the stars are not displayed but instead a drop-down menu to select the rating in addition of the submit rating button.
I tried to add these few lines so that the rating is display correctly but it does not work.

This is the an extract of the view template that uses the rateable plugin as

```
            <rateable:ratings bean='${photoInstance}' id="photo${photoInstance.id}"/>



    <g:if test="${request.xhr}">
        <script type="text/javascript" src="${resource(dir: '../target/plugins/yui-2.8.2.1/web-app/js/yui/yahoo-dom-event/', file: 'yahoo-dom-event.js')}"></script>
        <script type="text/javascript" src="${resource(dir: '../target/plugins/yui-2.8.2.1/web-app/js/yui/connection/', file: 'connection.js')}"></script>
        <script type="text/javascript" src="${resource(dir: '../target/plugins/rateable-0.7.1/web-app/js', file: 'ratings.js')}"></script>
        <link rel="stylesheet" href="${createLinkTo(dir: '../target/plugins/rateable-0.7.1/web-app/css', file: 'ratings.css')}" />

        <r:layoutResources disposition="defer"/>
    </g:if> 
```

Please can you help me work around this issue

Thanks a lot,

Regards,

**Comment by viseth** [comment]
Hi anyone,

Working with rateable plugins and face this use case?

thanks

regards

\Viseth

**Comment by graemerocher** [comment]
Since the plugin no longer users YUI and has been upgraded to Grails 3.0, closing this as old
